### ISSUE TITLE
add caching

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/oghunt#15]
use nextjs fetch cache prolly

**Comment by chadstewart** [comment]
So in Next.js 14, Next automagically caches all get requests made by fetch by default. You don't need to configure anything in Next.js to use caching unless you want Next.js to not cache as aggressively.

Note, this will be changed in Next.js 15 and I believe is currently this way in their current release candidate as their docs have already changed to reflect this.

**Comment by Hacksore** [comment]
@chadstewart i don't think built in caching is going to work because we have to collect many paged requests.

Hoping the @bautistaaa can tell us the way!

**Comment by Hacksore** [comment]
The plan is likely cron job on github action to fetch the data and store in r2.

Next app can pull from the r2 bucket to get the data. This will complicate the local DX so will have to code in account for that.

**Comment by Hacksore** [comment]
Date from the `getAllPosts` method is now auto uploaded to R2 every hour part of [this github action script](https://github.com/Hacksore/oghunt/blob/yippe/.github/workflows/data-fetcher.yaml).

artifact: https://pub-3db3ed9313c4427fadfa81f0323b18f8.r2.dev/latest.json
manual run: https://github.com/Hacksore/oghunt/actions/runs/10472364030

**Comment by chadstewart** [comment]
**My face after I went looking for the PR to rocketship only to realize @Hacksore force pushed to main (yippe)**

![whatever](https://github.com/user-attachments/assets/f63582ca-79e3-47e5-914e-dbed0ab218fe)

**Comment by Hacksore** [comment]
@chadstewart 
![tenor](https://github.com/user-attachments/assets/2f44ed34-6d29-4644-be4f-ca03a067e3c6)
