### ISSUE TITLE
redesign the number count

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/oghunt#22]
we should make these not confusing and have the the count be like `#1`, `#2` etc and move them off to the left moar
![image](https://github.com/user-attachments/assets/29fc20ad-4274-4411-9598-f2eada7a712c)

**Comment by Hacksore** [comment]
simple mock 
![image](https://github.com/user-attachments/assets/4c9da2d2-e559-4977-b244-744b15cfee8f)

**Comment by MVAodhan** [comment]
put me in coach

**Comment by Hacksore** [comment]
@MVAodhan might want to be careful with this one as this is a bit conflicting #33

**Comment by MVAodhan** [comment]
> @MVAodhan might want to be careful with this one as this is a bit conflicting #33

So not like your simple mock? 

I'll give it a good go like the thumbnails

**Comment by Hacksore** [comment]
giving this to @Kampouse since he has a PR up

**Comment by MVAodhan** [comment]
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGczZHZwaGZtM2lrcG9xYXZ4eDYzMXpueHR6eDRubmplYTRzaTR0dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/G4ZNYMQVMH6us/giphy.gif
