### ISSUE TITLE
add error page

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/oghunt#26]
add an `error.tsx` if we get errors, need to handle error state in graphql response?

**Comment by BostonRohan** [comment]
we are 10x devs so we will never get errors, but I can take this one in the rare case that there is a skill issue and an error occurs.

**Comment by Hacksore** [comment]
@BostonRohan all you brotha!

**Comment by BostonRohan** [comment]
@swalker326 you are a good man. many blessings
