### ISSUE TITLE
light mode is 🐶 

### ISSUE THREAD

**Issue by ajchili** [Hacksore/oghunt#35]
<img width="1840" alt="image" src="https://github.com/user-attachments/assets/c469c00c-75e9-4a28-89f0-6febdb02516b">

I cannot read this, partially because light mode blinded me, but mainly because the styles are not ideal.

**Comment by JoshHyde9** [comment]
I can cook on this if you'd like

**Comment by JoshHyde9** [comment]
![image](https://github.com/user-attachments/assets/e797a8bd-4ace-494b-83a3-83198034eb12)

This is what I got rn. On light theme, the orange and pink darken if that's okay

**Comment by JoshHyde9** [comment]
![image](https://github.com/user-attachments/assets/324944bb-572e-4346-a0a2-02a30be56793)

Updated with @LucFauvel PR
