### ISSUE TITLE
add star on github badge

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/oghunt#44]
![image](https://github.com/user-attachments/assets/8663e474-7a87-42b0-92ea-a340bfd7e65c)
![image](https://github.com/user-attachments/assets/41e81e99-8b8c-46d7-9abe-f4a2e5f9e44b)
![image](https://github.com/user-attachments/assets/9a96d813-e50d-4f86-a391-bfcc8b229e71)
![image](https://github.com/user-attachments/assets/ff144a3d-3004-4193-b2c4-b4ffa7b6f070)
![image](https://github.com/user-attachments/assets/8b1168af-ed0e-4723-af5c-1e28ec823bbd)

**Comment by ArcherScript** [comment]
where

**Comment by Hacksore** [comment]
@ArcherScript i think anywhere tbh

**Comment by ArcherScript** [comment]
I'm claiming this one

**Comment by ArcherScript** [comment]
![image](https://github.com/user-attachments/assets/871ba602-2085-4ff0-8d15-b7c0b29a5523)
I tried, looks like shit. Need PM @Hacksore

**Comment by JoshHyde9** [comment]
Was someone still cooking on this or nah?

**Comment by JoshHyde9** [comment]
All yours @maxdemaio!
