### ISSUE TITLE
add bust cache route

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/oghunt#46]
since we ISR we should add GET `/api/bust?uWuKey=<superSekritToken>` so that we we need to bust cache in prod we can.

- it should check the  `uWuKey` === `process.env.CACHE_BUST_UWU_KEY`
- when it matches call `revalidatePath("/")` ([sauce](https://nextjs.org/docs/app/building-your-application/data-fetching/caching-and-revalidating#on-demand-revalidation)) to bust the cache
- update the docs for new sekrit or disable it in dev mode
- profit

**Comment by ArcherScript** [comment]
https://tenor.com/view/shrek-meme-shrek-hmm-gif-15171325527464446560

**Comment by ArcherScript** [comment]
![shrek-meme-shrek-hmm](https://github.com/user-attachments/assets/3705a385-a587-4f8c-96f1-fb5065969a8f)
