### ISSUE TITLE
Topics stored in db are malformed

### ISSUE THREAD

**Issue by JoshHyde9** [Hacksore/oghunt#61]
Some don't have topics: 
![image](https://github.com/user-attachments/assets/445e0917-caa3-4be7-bcb7-e7d0e03d1983)
![image](https://github.com/user-attachments/assets/19811e56-16a9-43c0-9cd2-79f7c125f6b4)

Some only have 1 or 2 topics:  
![image](https://github.com/user-attachments/assets/0a08fd63-5e47-407d-8140-5492a7e27525)
![image](https://github.com/user-attachments/assets/a9820a93-4d81-4b7f-94c7-f6da8e42518e)

**Comment by maxdemaio** [comment]
Good catch brotherman 👀

**Comment by Hacksore** [comment]
I think it’s this whole spaghetti https://github.com/Hacksore/oghunt/blob/845435def016cbb4377c1d2748e811006bfd9bfe/src/app/lib/persistence.ts#L69

Last night I got rate limited so I rage quit 😂

**Comment by Hacksore** [comment]
@typesafeui you fix this one brother

**Comment by typesafeui** [comment]
the prisma lgtm are you sure the id is unique/present?

**Comment by typesafeui** [comment]
Found the issue the schema is wrong, you didn't merge in the changes I suggested
