### ISSUE TITLE
add plug page for the homies

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/oghunt#76]
We can have a /plug or something that lists all the homies projects

- Overlayed
- flosa
- Typehero
- Seattle safe eats
- Splist
- etc

**Comment by Kampouse** [comment]
should there be  some  visual clue from the home that this existe ??

**Comment by Kampouse** [comment]
we could use the same layout as the main  site but with homies projects?

**Comment by Hacksore** [comment]
Yes and yes @Kampouse

**Comment by Hacksore** [comment]
@maxdemaio @ArcherScript y’all can update yours check projects.ts

https://oghunt.com/homies
